apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: apitest
spec:
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-container
        image: jorgeabrego/my-fastapi-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000