apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: apitest
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
  selector:
    app: fastapi-app